# 需要自动构建的Docker镜像配置
repositories:
  - name: realm
    repo_url: https://github.com/zhboner/realm.git
    branch: master
    release_name: realm-x86_64-unknown-linux-musl.tar.gz

  - name: reality
    repo_url: https://github.com/XTLS/Xray-core.git
    branch: main

  - name: mermaid-live-editor
    repo_url: https://github.com/mermaid-js/mermaid-live-editor.git
    branch: develop

  - name: qwerty-learner
    repo_url: https://github.com/RealKai42/qwerty-learner.git
    branch: main
    